// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlibustierClient is the client API for Flibustier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlibustierClient interface {
	GlobalSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	CheckUpdates(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error)
}

type flibustierClient struct {
	cc grpc.ClientConnInterface
}

func NewFlibustierClient(cc grpc.ClientConnInterface) FlibustierClient {
	return &flibustierClient{cc}
}

func (c *flibustierClient) GlobalSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/flibustier.Flibustier/GlobalSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flibustierClient) CheckUpdates(ctx context.Context, in *UpdateCheckRequest, opts ...grpc.CallOption) (*UpdateCheckResponse, error) {
	out := new(UpdateCheckResponse)
	err := c.cc.Invoke(ctx, "/flibustier.Flibustier/CheckUpdates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlibustierServer is the server API for Flibustier service.
// All implementations must embed UnimplementedFlibustierServer
// for forward compatibility
type FlibustierServer interface {
	GlobalSearch(context.Context, *SearchRequest) (*SearchResponse, error)
	CheckUpdates(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error)
	mustEmbedUnimplementedFlibustierServer()
}

// UnimplementedFlibustierServer must be embedded to have forward compatible implementations.
type UnimplementedFlibustierServer struct {
}

func (UnimplementedFlibustierServer) GlobalSearch(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GlobalSearch not implemented")
}
func (UnimplementedFlibustierServer) CheckUpdates(context.Context, *UpdateCheckRequest) (*UpdateCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUpdates not implemented")
}
func (UnimplementedFlibustierServer) mustEmbedUnimplementedFlibustierServer() {}

// UnsafeFlibustierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlibustierServer will
// result in compilation errors.
type UnsafeFlibustierServer interface {
	mustEmbedUnimplementedFlibustierServer()
}

func RegisterFlibustierServer(s grpc.ServiceRegistrar, srv FlibustierServer) {
	s.RegisterService(&Flibustier_ServiceDesc, srv)
}

func _Flibustier_GlobalSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlibustierServer).GlobalSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flibustier.Flibustier/GlobalSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlibustierServer).GlobalSearch(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flibustier_CheckUpdates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlibustierServer).CheckUpdates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/flibustier.Flibustier/CheckUpdates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlibustierServer).CheckUpdates(ctx, req.(*UpdateCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Flibustier_ServiceDesc is the grpc.ServiceDesc for Flibustier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flibustier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flibustier.Flibustier",
	HandlerType: (*FlibustierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GlobalSearch",
			Handler:    _Flibustier_GlobalSearch_Handler,
		},
		{
			MethodName: "CheckUpdates",
			Handler:    _Flibustier_CheckUpdates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flibustier.proto",
}
