// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: flibustier.proto

//
//To compile:
//
//protoc --go_out=. --go_opt=paths=source_relative \
//--go-grpc_out=. --go-grpc_opt=paths=source_relative flibustier.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoundEntry_FoundEntryType int32

const (
	FoundEntry_UNKNOWN FoundEntry_FoundEntryType = 0
	FoundEntry_SERIES  FoundEntry_FoundEntryType = 1
	FoundEntry_AUTHOR  FoundEntry_FoundEntryType = 2
	FoundEntry_BOOK    FoundEntry_FoundEntryType = 3
)

// Enum value maps for FoundEntry_FoundEntryType.
var (
	FoundEntry_FoundEntryType_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERIES",
		2: "AUTHOR",
		3: "BOOK",
	}
	FoundEntry_FoundEntryType_value = map[string]int32{
		"UNKNOWN": 0,
		"SERIES":  1,
		"AUTHOR":  2,
		"BOOK":    3,
	}
)

func (x FoundEntry_FoundEntryType) Enum() *FoundEntry_FoundEntryType {
	p := new(FoundEntry_FoundEntryType)
	*p = x
	return p
}

func (x FoundEntry_FoundEntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FoundEntry_FoundEntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_flibustier_proto_enumTypes[0].Descriptor()
}

func (FoundEntry_FoundEntryType) Type() protoreflect.EnumType {
	return &file_flibustier_proto_enumTypes[0]
}

func (x FoundEntry_FoundEntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FoundEntry_FoundEntryType.Descriptor instead.
func (FoundEntry_FoundEntryType) EnumDescriptor() ([]byte, []int) {
	return file_flibustier_proto_rawDescGZIP(), []int{1, 0}
}

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchTerm string `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flibustier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flibustier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_flibustier_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type FoundEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryType   FoundEntry_FoundEntryType `protobuf:"varint,1,opt,name=entry_type,json=entryType,proto3,enum=flibustier.FoundEntry_FoundEntryType" json:"entry_type,omitempty"`
	EntryName   string                    `protobuf:"bytes,2,opt,name=entry_name,json=entryName,proto3" json:"entry_name,omitempty"`
	Author      string                    `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	EntryId     int64                     `protobuf:"varint,4,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	NumEntities int32                     `protobuf:"varint,5,opt,name=num_entities,json=numEntities,proto3" json:"num_entities,omitempty"`
}

func (x *FoundEntry) Reset() {
	*x = FoundEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flibustier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoundEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundEntry) ProtoMessage() {}

func (x *FoundEntry) ProtoReflect() protoreflect.Message {
	mi := &file_flibustier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundEntry.ProtoReflect.Descriptor instead.
func (*FoundEntry) Descriptor() ([]byte, []int) {
	return file_flibustier_proto_rawDescGZIP(), []int{1}
}

func (x *FoundEntry) GetEntryType() FoundEntry_FoundEntryType {
	if x != nil {
		return x.EntryType
	}
	return FoundEntry_UNKNOWN
}

func (x *FoundEntry) GetEntryName() string {
	if x != nil {
		return x.EntryName
	}
	return ""
}

func (x *FoundEntry) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FoundEntry) GetEntryId() int64 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *FoundEntry) GetNumEntities() int32 {
	if x != nil {
		return x.NumEntities
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OriginalRequest *SearchRequest `protobuf:"bytes,1,opt,name=original_request,json=originalRequest,proto3" json:"original_request,omitempty"`
	Entry           []*FoundEntry  `protobuf:"bytes,2,rep,name=entry,proto3" json:"entry,omitempty"`
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_flibustier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flibustier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_flibustier_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetOriginalRequest() *SearchRequest {
	if x != nil {
		return x.OriginalRequest
	}
	return nil
}

func (x *SearchResponse) GetEntry() []*FoundEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

var File_flibustier_proto protoreflect.FileDescriptor

var file_flibustier_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72, 0x22, 0x30,
	0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d,
	0x22, 0x88, 0x02, 0x0a, 0x0a, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x44, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72,
	0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x46, 0x6f, 0x75, 0x6e,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x65, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6e,
	0x75, 0x6d, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x0e, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x45, 0x52,
	0x49, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x10,
	0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4b, 0x10, 0x03, 0x22, 0x84, 0x01, 0x0a, 0x0e,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x10, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x66, 0x6c, 0x69, 0x62, 0x75,
	0x73, 0x74, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x52, 0x0f, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72,
	0x2e, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x65, 0x6e, 0x74,
	0x72, 0x79, 0x32, 0x55, 0x0a, 0x0a, 0x46, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72,
	0x12, 0x47, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x19, 0x2e, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x66, 0x6c,
	0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x51, 0x0a, 0x18, 0x63, 0x6f, 0x6d,
	0x2e, 0x73, 0x67, 0x7a, 0x6d, 0x64, 0x2e, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65,
	0x72, 0x2e, 0x72, 0x70, 0x63, 0x42, 0x0f, 0x46, 0x6c, 0x69, 0x62, 0x75, 0x73, 0x74, 0x69, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x22, 0x66, 0x6c, 0x69, 0x62, 0x75, 0x73,
	0x74, 0x61, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x2f, 0x66, 0x6c, 0x69, 0x62, 0x75,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_flibustier_proto_rawDescOnce sync.Once
	file_flibustier_proto_rawDescData = file_flibustier_proto_rawDesc
)

func file_flibustier_proto_rawDescGZIP() []byte {
	file_flibustier_proto_rawDescOnce.Do(func() {
		file_flibustier_proto_rawDescData = protoimpl.X.CompressGZIP(file_flibustier_proto_rawDescData)
	})
	return file_flibustier_proto_rawDescData
}

var file_flibustier_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flibustier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_flibustier_proto_goTypes = []interface{}{
	(FoundEntry_FoundEntryType)(0), // 0: flibustier.FoundEntry.FoundEntryType
	(*SearchRequest)(nil),          // 1: flibustier.SearchRequest
	(*FoundEntry)(nil),             // 2: flibustier.FoundEntry
	(*SearchResponse)(nil),         // 3: flibustier.SearchResponse
}
var file_flibustier_proto_depIdxs = []int32{
	0, // 0: flibustier.FoundEntry.entry_type:type_name -> flibustier.FoundEntry.FoundEntryType
	1, // 1: flibustier.SearchResponse.original_request:type_name -> flibustier.SearchRequest
	2, // 2: flibustier.SearchResponse.entry:type_name -> flibustier.FoundEntry
	1, // 3: flibustier.Flibustier.GlobalSearch:input_type -> flibustier.SearchRequest
	3, // 4: flibustier.Flibustier.GlobalSearch:output_type -> flibustier.SearchResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_flibustier_proto_init() }
func file_flibustier_proto_init() {
	if File_flibustier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_flibustier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flibustier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoundEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_flibustier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flibustier_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flibustier_proto_goTypes,
		DependencyIndexes: file_flibustier_proto_depIdxs,
		EnumInfos:         file_flibustier_proto_enumTypes,
		MessageInfos:      file_flibustier_proto_msgTypes,
	}.Build()
	File_flibustier_proto = out.File
	file_flibustier_proto_rawDesc = nil
	file_flibustier_proto_goTypes = nil
	file_flibustier_proto_depIdxs = nil
}
