server:
  port: 8443
  servlet:
    session:
      tracking-modes: cookie
  # For development only!
  ssl:
    key-store-type: PKCS12
    key-store: /home/sgzmd/code/flibustier/config/keystore.p12
    key-store-password: 123456
    key-alias: tomcat

security:
  require-ssl: true

spring:
  thymeleaf:
    cache: false
