spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true



dev:
  userId: 1

flibusta:
  dburl: "jdbc:sqlite:../data/flibusta.db"