spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    url: jdbc:h2:file:../h2.db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# spring.jpa.hibernate.ddl-auto

dev:
  userId: 1

flibusta:
  dburl: "jdbc:sqlite:../data/flibusta.db"