spring:
  devtools:
    livereload:
      port: 35730
  datasource:
    url: jdbc:h2:file:../h2.db;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  mail:
    host: localhost

dev:
  userId: 1



server:
  use-forwarded-headers: true

flibusta:
  dburl: "jdbc:sqlite:../data/flibusta.db"
  rpc:
    host: "localhost"
    port: 9000

smtp:
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
